wiki/encyclopedia/urls.py
from django.urls import path

from . import views

# This app_name is not acc needed bc we only have 1 app,
# but it's worth having in case we have multiple apps.
# What it makes is, in case we add a link, it lets Django 
# find out what app you're refering to when linking.
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("404", views.error_404, name="404"),
    path("entries/<str:entry_title>", views.content_page, name="contentPage")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from xml.dom import ValidationErr
from .util import get_entry, render_markdown_to_html
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from django import forms
from django.http import Http404
from .util import get_entry 

from . import util

entries = []
class NewEntryForm(forms.Form):
    entry = forms.CharField(label="Title")
    content = forms.CharField(label="Content", widget=forms.Textarea)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# Esto crea una vista separada para la página 404. 
def error_404(request):
    return render(request, "encyclopedia/404.html")


def content_page(request, entry_title):
    content = get_entry(entry_title)
    if content is None:
        raise Http404("Entry not found")
    
    return render(request, "encyclopedia/contentPage.html", {
        "title": entry_title,
        "content": content,
    })

def add(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            entry = form.cleaned_data["entry"]
            content = form.cleaned_data["content"]
            try: 
                util.save_entry(entry, content)
                # Esto guarda la entrada utilizando la función save_entry de util
                return redirect("encyclopedia:index")
            except ValidationError as e:
                return redirect("encyclopedia:404")
        else:
            return redirect("encyclopedia:404")
    return render(request, "encyclopedia/add.html",{
        "form": NewEntryForm()
    })

def view_entry(request, entry_title):
    content = get_entry(entry_title)
    if content is None:
        raise Http404("Entry not found")
    
    html_content = render_markdown_to_html(content)

    return render(request, "encyclopedia/contentPage.html", {
        "title": entry_title,
        "content": html_content,
    })

wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block body%}
    <h1>Add an entry</h1>
    <form action="{% url 'encyclopedia:add' %}" method="post">
        <!-- Este token viene de settings.py dentro de middleware 'django.middleware.csrf.CsrfViewMiddleware'-->
        <!-- Encripta la información que introducimos para que no sea vulnerable-->
        {% csrf_token %}
        <!-- Esto hace una llamada a views.py donde hemos creado la clase NewEntryForm-->
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/contentPage.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>{{ title }}</h1>
    <!--Al poner |safe le indidamos a django que 
    el contenido ya ha sido sanitizado y es seguro de renderizar como HTML-->
    <div>{{ content|safe }}</div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li>
            <a href="/entries/{{ entry }}">{{ entry }}</a>
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'encyclopedia:add' %}">Add a new entry</a>
    <!-- Aquí va a urls y busca la url que se llame add-->
    <!-- No es necesario poner el encyclopedia:add porque solo hay una app-->
    <!-- Pero al haber añadido en urls.py app_name = "encyclopedia", hay que ponerlo-->

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>